### ISSUE TITLE
Problème de partage BSATool

### ISSUE THREAD

**Issue by ghost** [Dysperia/ArenaToolBox-BSATool#2]
Salut Dysperia, J'ai voulu télécharger le Arena ToolBox et on m'a envoyé ici. Seulement, je n'ai aucune idée comment utiliser des source code pour former un executable et comme je sais que d'autres personnes cherchent aussi à utiliser ton outil pour modder Arena, Pourrais tu construire l'éxécutable de la dernière version (1.2) ? J'ai essayé avec quelques programmes, mais je n'y arrive pas. Merci pour ton temps.

**Comment by Dysperia** [comment]
Bonjour, je devrais en effet lier le dépôt au projet de base pour que les gens puisse se rediriger vers les exécutables. Je complète le README tout de suite.

Dysperia
